<a href="https://colab.research.google.com/github/Sauber59/machine-learning-bootcamp/blob/main/supervised%20/01_basics/04_train_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns

np.random.seed(42)
np.set_printoptions(edgeitems = 30, linewidth= 100000, formatter=dict(float=lambda x: f'{x:.2f}'))

sns.set()


##Zaladowanie danych

In [7]:
from sklearn.datasets import load_iris

raw_data = load_iris()
raw_data_copy = raw_data.copy()
raw_data_copy.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [12]:
print(raw_data_copy['target_names'])

{'data': array([[5.10, 3.50, 1.40, 0.20],
        [4.90, 3.00, 1.40, 0.20],
        [4.70, 3.20, 1.30, 0.20],
        [4.60, 3.10, 1.50, 0.20],
        [5.00, 3.60, 1.40, 0.20],
        [5.40, 3.90, 1.70, 0.40],
        [4.60, 3.40, 1.40, 0.30],
        [5.00, 3.40, 1.50, 0.20],
        [4.40, 2.90, 1.40, 0.20],
        [4.90, 3.10, 1.50, 0.10],
        [5.40, 3.70, 1.50, 0.20],
        [4.80, 3.40, 1.60, 0.20],
        [4.80, 3.00, 1.40, 0.10],
        [4.30, 3.00, 1.10, 0.10],
        [5.80, 4.00, 1.20, 0.20],
        [5.70, 4.40, 1.50, 0.40],
        [5.40, 3.90, 1.30, 0.40],
        [5.10, 3.50, 1.40, 0.30],
        [5.70, 3.80, 1.70, 0.30],
        [5.10, 3.80, 1.50, 0.30],
        [5.40, 3.40, 1.70, 0.20],
        [5.10, 3.70, 1.50, 0.40],
        [4.60, 3.60, 1.00, 0.20],
        [5.10, 3.30, 1.70, 0.50],
        [4.80, 3.40, 1.90, 0.20],
        [5.00, 3.00, 1.60, 0.20],
        [5.00, 3.40, 1.60, 0.40],
        [5.20, 3.50, 1.50, 0.20],
        [5.20, 3.40, 1.40, 0.20],
      

##Przygotowanaie danych

In [18]:
data = raw_data_copy['data']
target = raw_data_copy['target']

print(f'{data[:5]}\n')
print(target[:5])

[[5.10 3.50 1.40 0.20]
 [4.90 3.00 1.40 0.20]
 [4.70 3.20 1.30 0.20]
 [4.60 3.10 1.50 0.20]
 [5.00 3.60 1.40 0.20]]

[0 0 0 0 0]


#Zamiana na dataframe

In [22]:
all_data = np.c_[data, target]
df = pd.DataFrame(data=all_data, columns=raw_data.feature_names + ['target'])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [25]:
 data = df.copy()
 target = data.pop('target')
 data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

##Podzial danych na zbior treningowy i testowy

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

print(f'X_train shape {X_train.shape}')
print(f'y_train shape {y_train.shape}')
print(f'X_test shape {X_test.shape}')
print(f'y_test shape {y_test.shape}')
print(f'\nTest ratio: {len(X_test) / len(data):.2f}')
print(f'\ny_train:\n{y_train.value_counts()}')
print(f'\ny_test:\n{y_test.value_counts()}')

X_train shape (112, 4)
y_train shape (112,)
X_test shape (38, 4)
y_test shape (38,)

Test ratio: 0.25

y_train:
target
1.0    39
2.0    38
0.0    35
Name: count, dtype: int64

y_test:
target
0.0    15
2.0    12
1.0    11
Name: count, dtype: int64


In [27]:
#zmiana proporcji danych testowych (test_size)
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42, test_size=0.3)

print(f'X_train shape {X_train.shape}')
print(f'y_train shape {y_train.shape}')
print(f'X_test shape {X_test.shape}')
print(f'y_test shape {y_test.shape}')
print(f'\nTest ratio: {len(X_test) / len(data):.2f}')
print(f'\ny_train:\n{y_train.value_counts()}')
print(f'\ny_test:\n{y_test.value_counts()}')

X_train shape (105, 4)
y_train shape (105,)
X_test shape (45, 4)
y_test shape (45,)

Test ratio: 0.30

y_train:
target
1.0    37
2.0    37
0.0    31
Name: count, dtype: int64

y_test:
target
0.0    19
1.0    13
2.0    13
Name: count, dtype: int64


In [31]:
#rowny podzial ze wzgledu na zmienna docelowa (stratify)
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42, test_size=0.1, stratify=target)

print(f'X_train shape {X_train.shape}')
print(f'y_train shape {y_train.shape}')
print(f'X_test shape {X_test.shape}')
print(f'y_test shape {y_test.shape}')
print(f'\nTest ratio: {len(X_test) / len(data):.2f}')
print(f'\ny_train:\n{y_train.value_counts()}')
print(f'\ny_test:\n{y_test.value_counts()}')

X_train shape (135, 4)
y_train shape (135,)
X_test shape (15, 4)
y_test shape (15,)

Test ratio: 0.10

y_train:
target
0.0    45
2.0    45
1.0    45
Name: count, dtype: int64

y_test:
target
1.0    5
2.0    5
0.0    5
Name: count, dtype: int64


##Inny przyklad danych

In [34]:
from sklearn.datasets import load_breast_cancer

raw_data = load_breast_cancer()
raw_data_copy = raw_data.copy()
raw_data_copy.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])